### ISSUE TITLE
'-' or '_' in AVP names?

### ISSUE THREAD

**Issue by haussli** [haussli/draft-dahm-tacacs-security#15]
I mixed the new '-' or '_' in AVP names.  ssh_pubkey_type, ssh_pubkey, ssh-subsystem.  Does this matter?  Douglas told me once of the common practice, but I have forgotten.  IIRC, ssh-subsystem with the '-' came from the SSH RFCs.

**Comment by td-tacacs** [comment]
I would aim to be consistent troughout the document. FWIW, my preference would be to use '_'

**Comment by hassiosni** [comment]
I think this is where Douglas' comment from #12 belongs:
"I guess the challenge is, this will mean that the ssh_pubkey_type is no longer exactly the same as in the SSH RFCs?"

It might be only ssh-subsystem that is defined in the RFCs.  We would need to research this.

**Comment by haussli** [comment]
I thought that I had chosen '-' in ssh-subsystem specifically to match a spec/rfc, but I can not it. Made the replacement in bdef7d4359.
