### ISSUE TITLE
Should an AVP be able to span multiple packets (Raised by John)

### ISSUE THREAD

**Issue by dcmgashcisco** [haussli/draft-dahm-tacacs-security#2]
- should an AVP be allowed to span multiple packets?  ie: that
the packet payload should be concatenated.  This has implications
for more than just ssh pubkeys.

**Comment by td-goog** [comment]
Without thinking it trough too much, I'd say no, so we can avoid having to think about fragmentation. Do we expect AVP pairs that would be too big for a single packet?

**Comment by haussli** [comment]
I will ensure that this is documented in our draft.
