### ISSUE TITLE
TLS musing

### ISSUE THREAD

**Issue by haussli** [haussli/draft-dahm-tacacs-security#30]
We asked ourselves the following questions about TLS support:
* How adamant are we that PSKs must be supported?
* will the WG require certificates?  Do we not want them?
* will the WG require TLS 1.3?  Its the shiney thing, but is it required?
* With certificates, how is domain isolation from CAs handled?

The conclusion is we will try pointing toward rfc8996 for which TLS versions must be supported and require support for TLS certificate authentication.  We will not mention certificate handling.  We will not mention TLS PSKs and wait to see if the WG mentions it.  We might add a section to describe operator deployment considerations, such as isolation from CAs.

Call notes follow:
Try to avoid unnecessary detail and vendor/implementation-specific information in the draft.

  support certificates & mutual authentication.
        can resist known security issues, such as a client connecting to
        any sever.  likewise a server could allow clients to take resources,
        DOS.

        are we comfortable accepting requirements for certificate
        authentication, or leaving it to best judgement?  do we care that,
        a client could connect to a rogue server and leak info this way?  or
        should we have a best-practices section where we suggest against this,
        as done in 8097 that PSK is recommended and must be handled properly,
        but this section about PSK handling and risks consumed a lot of effort.

        maybe suggest that <this handling is suggested>, b/c of <reasons>.

  speak in non-vendor specific terms only.  not how to handle the certificates
  themselves, but primary pitfalls to avoid

  Douglas finds himself thinking only PKI is required.  should we not mention
  PSK at all; if Peers support it, that is fine.  or say that any mutual auth mention is fine.

  could we say that you must support 1.2 and greater?  will 1.3 be considered
  part of that, from a lazy developer PoV?  could we just say 1.3 and greater?
  or point to rfc8996 (deprecation of 1.0 and 1.1) as the versions to support?

  we'll point to 8996 w/ 1.2 and forward....

  we'll note that isolation & certificate auth could be an issue.

**Comment by haussli** [comment]
To augment the previous comment, we've noted draft-ietf-tls-external-psk-guidance having information of interest for PSKs with TLS 1.3 and rfc9001 for another approach to specifying the addition of TLS to a protocol.

**Comment by dcmgashcisco** [comment]
The netconf RFC https://datatracker.ietf.org/doc/html/rfc7589 is also an interesting model that digs into the identity issue that Tom Petch raised. In old T+ client identity was not really regarded as a big thing, really the best we could do was a lookup table based on connection, and "authenticated" by the shared secret decode, assuming they were effectively managed. We have enhanced this with the "origin_client", which we could prbably deprecate if we manmdated PSK, and instead embed it in the subject of the cert CN,

Anyway, the Sections for NETCONF are:

1 Connection Initiation
2 Message Framing
3 Connection Closure
4 Certificate Validation
5 Server Identity
6 Client Identity
7 Cipher Suites

I think 1-4 in particular could be  useful to integrate into our model.

**Comment by haussli** [comment]
From the last meeting, creating an outline for the TLS text follows.

Generally, we should take a rfc5425-like (syslog TLS) approach, which is:
- requirements & why tls; which i think is already addressed in our draft
- how a tacacs connection with TLS is made, authenticated, and the life of such a connection
   * must support certificate authentication, with CA validation or certificate match (eg: self-signed), by both client and server
   * point to TLS RFCs recommendations for algorithm selection, but should be configurable
   * must we specify a TLS application data format?  Is it not just a serdes to the application?  syslog defines its in S4.3.1.
   * recommend no TLS "early data"
   * NO mention of TLS 1.2; 1.3 only (RFC8446)
- S8 Security Considerations/pitfalls & other TLS authen methods that could be used (TLS 1.3 PSK [draft-ietf-tls-external-psk-guidance], certificate fingerprints [rfc5425 S4.2.2, rfc4572 S5)

rfc6614 RADIUS TLS could be another reference model.

**Comment by haussli** [comment]
Notes from today's meeting.

- Perhaps take the union of last two comments in PR 30.
- identity - must define which fields/attirbutes must be filled to fulfill identity authentication
  Netconf TLS rfc7589 identity sections 5 & 6 might be a good model for T+ 
  
- douglas will research the TLS framing (tls application data format) question from the previous comment in this PR and TLS identity 
 
- should single-connection be recommended for TLS?
- is there a relation of a user concept of a session and tacacs concept of session that should be represented in TLS tacacs?  such as a token that the relates the two.

**Comment by haussli** [comment]
Coalescing the TLS outline comments from the last 24 hours:

- requirements & why tls; which i think is already addressed in our draft
- how a tacacs connection with TLS is made, authenticated, and the life of such a connection
  * must support certificate authentication, with CA validation or certificate match (eg: self-signed), by both client and server
  * point to TLS RFCs recommendations for algorithm selection, but should be configurable
  * must we specify a TLS application data format? Is it not just a serdes to the application? syslog defines its in S4.3.1.
  * recommend no TLS "early data"
  * NO mention of TLS 1.2; 1.3 only (RFC8446)
- S8 Security Considerations/pitfalls & other TLS authen methods that could be used (TLS 1.3 PSK [draft-ietf-tls-external-psk-guidance], certificate fingerprints [rfc5425 S4.2.2, rfc4572 S5)
  * PSK should not be shared among entities. a PSK could be stolen and used by rogue entity; an entity should (?) use the TCP connection source to further identify the peer?

This is incomplete, IMO.

**Comment by td-tacacs** [comment]
"PSK should not be shared among entities. a PSK could be stolen and used by rogue entity"

-> I would leave it at that, and delete the rest of the sentence IMHO. Thoughts?

**Comment by haussli** [comment]
Sure.  Truncated.

**Comment by haussli** [comment]
Responding to my own question in this PR about application data format ...

I do not understand why rfc5425 S4.3.1 (syslog over tls) specifies the application data in ABNF format.  I suspect that this might be due to mapping syslog to UDP or TCP, where some transport mapping require a length (TCP) and others do not (UDP).  See rfc5424 S6 for the syslog message spec in ABNF, which does not appear to have a length.  Length is discussed in S6.1 and A2.

And, see S3.4.1 of https://tools.ietf.org/id/draft-gerhards-syslog-plain-tcp-12.html which adds a length again in ABNF.

In SSL_read() and SSL_write() manpages, the api is clearly a stream format and the TLS library will perform its own record handling (splitting or coalescing) as specified in rfc8446 S5.1.   https://www.openssl.org/docs/man1.1.1/man3/SSL_read.html

The syslog data *is* application_data and can not be anything else, unless application data in early_data is handled some other way that I do not understand, which does not seem probable.

So, I am concluding that specifying a TLS application data format is entirely application-specific and no such specification is needed for tacacs.

**Comment by td-tacacs** [comment]
I agree with this statement: "So, I am concluding that specifying a TLS application data format is entirely application-specific and no such specification is needed for tacacs."

I came to the came conclustion when I looked at it.

**Comment by haussli** [comment]
Superseded by PR #44
