### ISSUE TITLE
TLS extended client hello server_name

### ISSUE THREAD

**Issue by haussli** [haussli/draft-dahm-tacacs-security#34]
https://datatracker.ietf.org/doc/html/rfc6066#section-3

Would this be useful for tacacs?  Could a client want to connect to multiple servers that might, unbeknowst to the client, reside on a single server at the same TCP port (ie: muxed)?

I suppose that a client could have multiple VRIs (Virtual Router Instances in a VRF-capable (Virtual Routing and Forwarding) device) or multi-tenant devices.  I would expect the AAA configuration to be separate and use unique source addresses, but that is not necessary.  Thinking GCP, AWS, DO.  Seems like this might be an unnecessary tangent for the target audience.

It would mean that TLS resumption nor TACACS+ Single Connection Mode could not be used, if the client used the same source address.

**Comment by dcmgashcisco** [comment]
This is interesting option. My initial reaction is that yes, it may be a little tangential for our target audience.

What has the responsibility for the de-multiplexing? Is the idea that we have one actual AA server but it has multiple instances inside itself? or is there a third component that does the TLS termination that intercepts this filed?

**Comment by haussli** [comment]
I think that de-muxing could be done by the tacacs daemon or a proxy.  But, yes, the AAA server can apply different policy based on the server name.

Maybe I am off course and this is an implementation detail that we should not consider?

**Comment by td-tacacs** [comment]
I would leave this one out of the RFC. If someone wants to implement the muxing, they can do so, but wearing my operations hat, I don't think I could come up with a scenario that would require a client connecting to multiple servers that reside on a single server at the same TCP port. Personally, I would in that situation opt for different ports since that would also make debugging etc. easier.

**Comment by haussli** [comment]
OK.
