### ISSUE TITLE
CRL

### ISSUE THREAD

**Issue by dcmgashcisco** [haussli/draft-dahm-tacacs-security#37]
Can we assume that be referring to RFC 5289 is enough to say that/whether CRL are/are not/must be supported

**Comment by td-tacacs** [comment]
I'd say yes.

**Comment by haussli** [comment]
I agree - or the WG will tell us otherwise :)

I think that an important point of distinction, afaik, is that CRL refers to a Certificate Revocation List (or revocations), which also must be supported but is just one aspect of Certificates.

**Comment by dcmgashcisco** [comment]
no update needed
