### ISSUE TITLE
Some XXX in text

### ISSUE THREAD

**Issue by dcmgashcisco** [haussli/draft-dahm-tacacs-security#38]
I am still seeing some XXX in the text in https://github.com/haussli/draft-dahm-tacacs-security/blob/master/draft-dahm-tacacs-security.xml, We should convert these to issues?

**Comment by haussli** [comment]
I think that is on the master, but have been eliminated in branch heas-tls, which I am about to merge.

**Comment by dcmgashcisco** [comment]
Looks good, closing
