### ISSUE TITLE
Suggestion in 3.1.  Well-Known TCP/IP Port

### ISSUE THREAD

**Issue by dcmgashcisco** [haussli/draft-dahm-tacacs-security#40]
Regarding: "It is not desirable to use a negotiation process such as a "STARTTLS"
   command, a feature that some protocols, which once existed without
   TLS, use to maintain backward compatibility.  Instead, following [RFC7605], ..."

That is true but we are a little coy about why ;-) how about instead something like:

"This document favors the predictable use of TLS security, over the backwards comparability of negotiation using STARTTLS command to secure an otherwise unsecured connection. TACACS+ TLS will therefore follow [RFC7605], where... "
 
   a different well-known system TCP/IP port is assigned by
   IANA, port [TBD] (Section 9), for the TLS connection."

**Comment by td-tacacs** [comment]
I like the new text suggested by Douglas :)

**Comment by haussli** [comment]
Not opposed to changing that, please feel free to change it (with the typo fixed).  However, is it already addressed by S 8.2, where the reasons are enumerated?  Or should 8.2 be changed or referenced from 3.1?

**Comment by haussli** [comment]
comparability -> compaTIbility.

**Comment by dcmgashcisco** [comment]
Agreed, let's make the reference to the security section rather than duplicating.

**Comment by haussli** [comment]
@dcmgashcisco will update S3.1 to reference 8.2.

**Comment by dcmgashcisco** [comment]
Merged fix
