### ISSUE TITLE
TLS resumption

### ISSUE THREAD

**Issue by haussli** [haussli/draft-dahm-tacacs-security#43]
We discussed today about whether or why we should mention TLS resumption in the draft or if any detail is missing.

Three reasons come to mind:

1. Because of the nature of the data, early data (aka 0-RTT) should not be used,
2. Though revocation of certificates is not immediate, resumption potentially worsens the delay by as much as 7 days unless ticket caches are flushed, so operators might wish to and should have the ability to disable resumption,
3. Operators should be able to disable resumptions, because in the presence of any-cast or load-balanced tacacs+ servers, the tickets must be shared among all potential servers for them to work, which is significantly complicated; though there is an alternative of allowing the resumption negotiation to fail when it encounters a server that does not have the ticket and restart the negotiation, that worsens TLS start-up performance.

I believe these are addressed in the current text, but all of the reasons might not be explained.

**Comment by haussli** [comment]
1. S8.1.2 explains 0-RTT
2. I've added S8.1.3 ("TLS Resumption Ticket Lifetime") to address this
3. S8.1.3

I've committed this on branch heas-43; 49ecc9d286c0131863efa701a2c9cfbe5841aebe
Someone needs to review this.

**Comment by haussli** [comment]
Incorporated Douglas' email comments in b536b56c30.

**Comment by td-tacacs** [comment]
Looks good to me as well, thanks John.

**Comment by haussli** [comment]
Merged.
