### ISSUE TITLE
Alan Dekok: existing TACACS+ port can be used for TLS

### ISSUE THREAD

**Issue by dcmgashcisco** [haussli/draft-dahm-tacacs-security#48]
This is a quick review based on first impressions.

  It may be good to have a note that the existing TACACS+ port can be used for TLS, if both ends are configured to require TLS.  That means systems can use existing firewall rules, etc. for TACACS+TLS.

**Comment by haussli** [comment]
Is it really necessary to explain this?  S3.1 and S8.2 explain allocation of a new port.  But, is there a service that does not allow the ports to be changed?

**Comment by haussli** [comment]
Noted that other ports could be used in be6a238.
