### ISSUE TITLE
Alan Dekok: zero-seconds lifetime resumption ticket_lifetime

### ISSUE THREAD

**Issue by dcmgashcisco** [haussli/draft-dahm-tacacs-security#49]
Section 3.2 says:

the resumption ticket_lifetime SHOULD be configurable, including a zero seconds lifetime.

  I'm not sure what a "zero-seconds lifetime" would mean.  It may be better to just omit the ticket in that case.

**Comment by haussli** [comment]
it means discard the ticket.  rfc 8446 S4.6.1

**Comment by haussli** [comment]
Migrating this PR to the TLS draft; https://github.com/haussli/draft-dahm-tacacs-tls13/issues/3
