### ISSUE TITLE
Alan Dekok: TLS Server Name Indication

### ISSUE THREAD

**Issue by dcmgashcisco** [haussli/draft-dahm-tacacs-security#50]
It would be good to mention that TLS Server Name Indication (SNI) SHOULD be supported (https://datatracker.ietf.org/doc/html/rfc6066#section-3).  That way one server can act as the TACACS+ host for multiple domains, and switch between them using SNI.

**Comment by haussli** [comment]
Issue 34 addressed this.  We closed it w/o addressing, thinking that there might not be desire for this.

Should we re-open 34?  Do so if there is more demand?  Wait for adoption?

**Comment by haussli** [comment]
Migrating this PR to the TLS draft; https://github.com/haussli/draft-dahm-tacacs-tls13/issues/2
